// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvezojmzooiyctnmyfys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZXpvam16b29peWN0bm15ZnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDIyNDUsImV4cCI6MjA1ODY3ODI0NX0.v2Ih9QFD3N9qDFDbP6MoASLpRZHbUcZG1Xj0FmyP4Lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);